const genres = [
  { id: 1, value: 0, label: 'All Genres' },
  { id: 12, value: 1, label: 'Adventure' },
  { id: 28, value: 2, label: 'Action' },
  { id: 16, value: 3, label: 'Animation' },
  { id: 35, value: 4, label: 'Comedy' },
  { id: 80, value: 5, label: 'Crime' },
  { id: 99, value: 6, label: 'Documentary' },
  { id: 18, value: 7, label: 'Drama' },
  { id: 10751, value: 8, label: 'Family' },
  { id: 14, value: 9, label: 'Fantasy' },
  { id: 36, value: 10, label: 'History' },
  { id: 27, value: 11, label: 'Horror' },
  { id: 10402, value: 12, label: 'Music' },
  { id: 9648, value: 13, label: 'Mystery' },
  { id: 10749, value: 14, label: 'Romance' },
  { id: 878, value: 15, label: 'Science Fiction' },
  { id: 10770, value: 16, label: 'TV Movie' },
  { id: 53, value: 17, label: 'Thriller' },
  { id: 10752, value: 18, label: 'War' },
  { id: 37, value: 19, label: 'Western' },
];
export default genres;
